version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${database_password}
      MYSQL_DATABASE: ${database_name}
      MYSQL_USER: ${database_username}
      MYSQL_PASSWORD: ${database_password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://{database_username}:{database_password}@{database_hostname}:{database_port}/{database_name}
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: